### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by BjornMelgaard** [flexxnn/sequelize-auto-migrations#4]
```
 ✘  ~/projects/rgs-decoupled   buffer ●  node ./node_modules/sequelize-auto-migrations/bin/makemigration --name create_db
module.js:491
    throw err;
    ^

Error: Cannot find module '/home/bjorn/projects/rgs-decoupled/models'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/bjorn/projects/rgs-decoupled/node_modules/sequelize-auto-migrations/bin/makemigration.js:53:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

```

**Comment by BjornMelgaard** [comment]
I had to create index.js with `sequalize init`
